services:

  mariadb:
    image: mariadb:10.11
    container_name: homelink-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: homelink
      MARIADB_USER: homelink_user
      MARIADB_PASSWORD: strongpassword
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db_data:
