.github/workflows/deploy-pages.yml,
name: Deploy Pages

on:
  push:
    branches:
      
main,

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
name: Checkout this repo
      uses: actions/checkout@v3,

      
name: Checkout source repo
      uses: actions/checkout@v3
      with:
        repository: oOmyLoveOo/Homelink
        path: Homelink,

      
name: Copy files
      run: |
        mkdir public
        cp -r Homelink/* public/,

      
name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
